apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "opsmate-operator.fullname" . }}-allow-metrics-traffic
  labels:
  {{- include "opsmate-operator.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          metrics: enabled
    ports:
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
  - Ingress