apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opsmate-operator.fullname" . }}-task-editor-role
  labels:
  {{- include "opsmate-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - sre.opsmate.io
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.opsmate.io
  resources:
  - tasks/status
  verbs:
  - get