// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplatev1alpha1 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Opsmate engineering team",
            "email": "jingkai@hey.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "get health check endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get health status of the API server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfov1alpha1 holds exported Swagger Info so clients can modify it
var SwaggerInfov1alpha1 = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1alpha1",
	Schemes:          []string{},
	Title:            "Opsmate Operator API",
	Description:      "This is Opsmate Operator API.",
	InfoInstanceName: "v1alpha1",
	SwaggerTemplate:  docTemplatev1alpha1,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfov1alpha1.InstanceName(), SwaggerInfov1alpha1)
}
