---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.opsmate.io
  resources:
  - envrionmentbuilds
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.opsmate.io
  resources:
  - envrionmentbuilds/finalizers
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - sre.opsmate.io
  resources:
  - envrionmentbuilds/status
  - tasks/status
  verbs:
  - get
  - patch
  - update
