apiVersion: sre.opsmate.io/v1alpha1
kind: EnvironmentBuild
metadata:
  labels:
    app.kubernetes.io/name: opsmate-operator
    app.kubernetes.io/managed-by: kustomize
  name: environmentbuild-sample
spec:
  template:
    spec:
      containers:
        - name: opsmate
          image: europe-west1-docker.pkg.dev/hjktech-metal/opsmate-images/opsmate:0.1.2.alpha3
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: opsmate-secret
