apiVersion: sre.opsmate.io/v1alpha1
kind: EnvrionmentBuild
metadata:
  labels:
    app.kubernetes.io/name: opsmate-operator
    app.kubernetes.io/managed-by: kustomize
  name: envrionmentbuild-sample
spec:
  # TODO(user): Add fields here
