apiVersion: sre.opsmate.io/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: opsmate-operator
    app.kubernetes.io/managed-by: kustomize
  name: task-sample
spec:
  userID: anonymous
  environmentBuildName: environmentbuild-sample
  description: "how many cpu cores on the server"
  context: "you are on a kubernetes cluster"
  domainName: "task-sample.opsmate.hjktech.io"
