//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvrionmentBuild) DeepCopyInto(out *EnvrionmentBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvrionmentBuild.
func (in *EnvrionmentBuild) DeepCopy() *EnvrionmentBuild {
	if in == nil {
		return nil
	}
	out := new(EnvrionmentBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvrionmentBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvrionmentBuildList) DeepCopyInto(out *EnvrionmentBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvrionmentBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvrionmentBuildList.
func (in *EnvrionmentBuildList) DeepCopy() *EnvrionmentBuildList {
	if in == nil {
		return nil
	}
	out := new(EnvrionmentBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvrionmentBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvrionmentBuildSpec) DeepCopyInto(out *EnvrionmentBuildSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvrionmentBuildSpec.
func (in *EnvrionmentBuildSpec) DeepCopy() *EnvrionmentBuildSpec {
	if in == nil {
		return nil
	}
	out := new(EnvrionmentBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvrionmentBuildStatus) DeepCopyInto(out *EnvrionmentBuildStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvrionmentBuildStatus.
func (in *EnvrionmentBuildStatus) DeepCopy() *EnvrionmentBuildStatus {
	if in == nil {
		return nil
	}
	out := new(EnvrionmentBuildStatus)
	in.DeepCopyInto(out)
	return out
}
